project_id = "qliinxtanjdnwxlvnxji"

[api]
enabled = true
port = 8081
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your magic link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm your email change"
content_path = "./supabase/templates/email_change.html"

[auth.sms]
template = "Your confirmation code is {{ .Code }} ."

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 8082
api_url = "http://127.0.0.1:8081"

[inbucket]
enabled = true
port = 8083
smtp_port = 8084
pop3_port = 8085

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 8086
vector_port = 8087

[functions.send-invitation]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[edge_runtime]
enabled = true

[db]
port = 8088
shadow_port = 8089
major_version = 15