#!/bin/bash

echo "🚀 DÉPLOIEMENT DES CORRECTIONS EMAIL CONFIRMATION"
echo "================================================="

echo ""
echo "1️⃣ Redéploiement de l'Edge Function avec nouvelle URL..."
supabase functions deploy send-invitation

echo ""
echo "2️⃣ Vérification que l'Edge Function handle-email-confirmation existe..."
supabase functions list | grep handle-email-confirmation || echo "⚠️ Edge Function handle-email-confirmation non trouvée"

echo ""
echo "3️⃣ Redémarrage du serveur de développement..."
echo "   Arrêtez le serveur actuel (Ctrl+C) puis relancez :"
echo "   npm run dev"

echo ""
echo "✅ CORRECTIONS DÉPLOYÉES !"
echo ""
echo "🔧 PROCHAINES ÉTAPES MANUELLES :"
echo "================================"
echo ""
echo "1. CONFIGURER LES URL DANS SUPABASE DASHBOARD :"
echo "   - URL: https://supabase.com/dashboard/project/qliinxtanjdnwxlvnxji"
echo "   - Authentication > URL Configuration"
echo "   - Site URL: http://localhost:8080"
echo "   - Additional Redirect URLs:"
echo "     * http://localhost:8080/auth/callback"
echo "     * http://localhost:8080/dashboard"
echo "     * http://localhost:8080/"
echo ""
echo "2. CONFIGURER LE WEBHOOK (OPTIONNEL) :"
echo "   - Database > Webhooks > Create a new hook"
echo "   - Name: email-confirmation-handler"
echo "   - Table: auth.users"
echo "   - Events: ☑️ Update"
echo "   - URL: https://qliinxtanjdnwxlvnxji.supabase.co/functions/v1/handle-email-confirmation"
echo "   - Condition: email_confirmed_at IS NOT NULL"
echo ""
echo "🎯 NOUVEAU FLUX :"
echo "================"
echo "1. Clic sur lien email → Supabase valide token"
echo "2. Redirection → /auth/callback (nouvelle page)"
echo "3. Page callback → Attend webhook + redirige dashboard"
echo "4. Processus fluide et automatique !"
echo ""
