-- Insertion des données d'exemple pour le système d'alertes

-- Types d'alertes (50 types différents)
INSERT INTO public.alert_types (code, name, description, category, severity) VALUES
('WORKLOAD_HIGH', 'Surcharge de travail', 'Employé avec une charge de travail excessive (>90%)', 'capacity', 'high'),
('ABSENCE_PATTERN', 'Pattern d''absences anormal', 'Augmentation significative des absences sur une période', 'hr', 'medium'),
('PERFORMANCE_DROP', 'Baisse de performance', 'Diminution notable des performances (-20%)', 'performance', 'medium'),
('DEADLINE_RISK', 'Risque d''échéance', 'Projet en retard ou à risque de dépassement', 'project', 'high'),
('TEAM_TURNOVER', 'Rotation d''équipe élevée', 'Turnover anormalement élevé (>15%/an)', 'hr', 'critical'),
('OVERTIME_EXCESSIVE', 'Heures supplémentaires excessives', 'Plus de 10h supplémentaires par semaine', 'capacity', 'high'),
('SICK_LEAVE_SPIKE', 'Pic d''arrêts maladie', 'Augmentation des arrêts maladie dans l''équipe', 'hr', 'medium'),
('BUDGET_OVERRUN', 'Dépassement budgétaire', 'Budget projet dépassé de plus de 15%', 'project', 'critical'),
('SKILL_GAP', 'Écart de compétences', 'Compétences insuffisantes pour les tâches assignées', 'performance', 'medium'),
('STRESS_INDICATOR', 'Indicateur de stress', 'Signaux de stress détectés chez l''employé', 'hr', 'high'),
('QUALITY_DECLINE', 'Baisse de qualité', 'Diminution de la qualité des livrables', 'performance', 'high'),
('COMMUNICATION_GAP', 'Défaut de communication', 'Manque de communication dans l''équipe', 'project', 'medium'),
('RESOURCE_CONFLICT', 'Conflit de ressources', 'Ressource assignée sur plusieurs projets', 'capacity', 'medium'),
('CLIENT_SATISFACTION', 'Satisfaction client faible', 'Score de satisfaction client en baisse', 'project', 'high'),
('TRAINING_OVERDUE', 'Formation en retard', 'Formation obligatoire non effectuée', 'hr', 'medium'),
('CAPACITY_UNDERUSED', 'Sous-utilisation', 'Employé avec charge de travail très faible (<30%)', 'capacity', 'low'),
('MEETING_OVERLOAD', 'Surcharge de réunions', 'Plus de 50% du temps en réunions', 'capacity', 'medium'),
('VACATION_BACKLOG', 'Arriéré de congés', 'Congés non pris accumulés', 'hr', 'low'),
('SECURITY_BREACH', 'Violation de sécurité', 'Incident de sécurité détecté', 'safety', 'critical'),
('EQUIPMENT_FAILURE', 'Panne d''équipement', 'Équipement critique en panne', 'safety', 'high'),
('COMPLIANCE_ISSUE', 'Problème de conformité', 'Non-conformité réglementaire détectée', 'hr', 'high'),
('KNOWLEDGE_LOSS', 'Perte de connaissances', 'Risque de perte de connaissances critiques', 'hr', 'medium'),
('PROCESS_BOTTLENECK', 'Goulot d''étranglement', 'Processus ralenti identifié', 'project', 'medium'),
('COST_ESCALATION', 'Escalade des coûts', 'Augmentation non planifiée des coûts', 'project', 'high'),
('DEPENDENCY_RISK', 'Risque de dépendance', 'Dépendance critique menacée', 'project', 'high'),
('INNOVATION_LAG', 'Retard d''innovation', 'Manque d''innovation dans l''équipe', 'performance', 'low'),
('CUSTOMER_CHURN', 'Désabonnement client', 'Risque de perte de client important', 'project', 'critical'),
('DATA_QUALITY', 'Qualité des données', 'Problème de qualité des données détecté', 'project', 'medium'),
('VENDOR_RISK', 'Risque fournisseur', 'Problème avec un fournisseur critique', 'project', 'high'),
('REGULATORY_CHANGE', 'Changement réglementaire', 'Nouvelle réglementation impactante', 'hr', 'medium'),
('MARKET_SHIFT', 'Évolution du marché', 'Changement majeur du marché', 'project', 'medium'),
('TECHNOLOGY_DEBT', 'Dette technique', 'Accumulation de dette technique', 'project', 'low'),
('TALENT_SHORTAGE', 'Pénurie de talents', 'Difficulté à recruter des profils', 'hr', 'high'),
('WORKPLACE_CONFLICT', 'Conflit au travail', 'Tension ou conflit dans l''équipe', 'hr', 'medium'),
('ERGONOMIC_ISSUE', 'Problème ergonomique', 'Risque ergonomique identifié', 'safety', 'medium'),
('ENVIRONMENTAL_RISK', 'Risque environnemental', 'Impact environnemental détecté', 'safety', 'medium'),
('PRODUCTIVITY_PLATEAU', 'Plateau de productivité', 'Stagnation de la productivité', 'performance', 'low'),
('SUCCESSION_RISK', 'Risque de succession', 'Manque de successeur pour poste clé', 'hr', 'high'),
('CULTURAL_MISALIGN', 'Désalignement culturel', 'Décalage avec la culture d''entreprise', 'hr', 'medium'),
('PROJECT_SCOPE_CREEP', 'Dérive du périmètre', 'Expansion non contrôlée du périmètre', 'project', 'medium'),
('INTELLECTUAL_PROP', 'Propriété intellectuelle', 'Risque sur la propriété intellectuelle', 'project', 'high'),
('EXTERNAL_DEPENDENCY', 'Dépendance externe', 'Forte dépendance à un acteur externe', 'project', 'medium'),
('CHANGE_RESISTANCE', 'Résistance au changement', 'Opposition aux changements organisationnels', 'hr', 'medium'),
('CAPACITY_MISMATCH', 'Décalage de capacité', 'Capacité inadaptée aux besoins', 'capacity', 'medium'),
('LEADERSHIP_GAP', 'Manque de leadership', 'Absence de leadership dans l''équipe', 'hr', 'high'),
('STRATEGIC_DRIFT', 'Dérive stratégique', 'Éloignement des objectifs stratégiques', 'project', 'high'),
('OPERATIONAL_INEFFI', 'Inefficacité opérationnelle', 'Processus opérationnels inefficaces', 'performance', 'medium'),
('STAKEHOLDER_DISENG', 'Désengagement parties prenantes', 'Perte d''engagement des parties prenantes', 'project', 'high'),
('REPUTATION_RISK', 'Risque de réputation', 'Menace sur la réputation de l''organisation', 'project', 'critical'),
('FINANCIAL_EXPOSURE', 'Exposition financière', 'Risque financier important identifié', 'project', 'critical');

-- Solutions (95 solutions différentes)
INSERT INTO public.alert_solutions (title, description, category, implementation_time, effectiveness_score, cost_level) VALUES
('Redistribution des tâches', 'Répartir les tâches vers d''autres membres de l''équipe moins chargés', 'capacity', 'immediate', 85, 'low'),
('Planification d''entretien individuel', 'Organiser un entretien pour comprendre les causes des problèmes', 'hr', 'short_term', 75, 'low'),
('Formation ciblée', 'Proposer une formation adaptée aux besoins identifiés', 'performance', 'long_term', 70, 'medium'),
('Extension de délai', 'Négocier une extension du délai avec le client ou parties prenantes', 'project', 'immediate', 60, 'low'),
('Plan de rétention', 'Mise en place d''un plan de rétention des talents', 'hr', 'long_term', 80, 'high'),
('Recrutement d''urgence', 'Lancer un processus de recrutement accéléré', 'capacity', 'short_term', 70, 'high'),
('Assistance temporaire', 'Faire appel à des consultants ou intérimaires', 'capacity', 'immediate', 65, 'high'),
('Révision des processus', 'Analyser et optimiser les processus existants', 'performance', 'long_term', 85, 'medium'),
('Communication renforcée', 'Améliorer la communication interne et externe', 'project', 'immediate', 70, 'low'),
('Mentorat et coaching', 'Mettre en place un programme de mentorat', 'hr', 'long_term', 80, 'medium'),
('Ajustement budgétaire', 'Réviser et ajuster le budget du projet', 'project', 'short_term', 75, 'low'),
('Automatisation', 'Automatiser les tâches répétitives et chronophages', 'performance', 'long_term', 90, 'high'),
('Réorganisation d''équipe', 'Restructurer l''organisation de l''équipe', 'hr', 'short_term', 70, 'medium'),
('Pause forcée', 'Imposer une pause ou congés pour éviter le burnout', 'hr', 'immediate', 80, 'low'),
('Analyse des causes racines', 'Effectuer une analyse approfondie des causes', 'project', 'short_term', 85, 'low'),
('Mise à jour des outils', 'Moderniser les outils et technologies utilisés', 'performance', 'long_term', 75, 'high'),
('Clarification des rôles', 'Redéfinir clairement les rôles et responsabilités', 'hr', 'short_term', 70, 'low'),
('Plan de contingence', 'Développer un plan de contingence détaillé', 'project', 'short_term', 80, 'medium'),
('Formation en leadership', 'Former les managers aux techniques de leadership', 'hr', 'long_term', 85, 'medium'),
('Revue de performance', 'Effectuer une revue de performance approfondie', 'performance', 'short_term', 75, 'low'),
('Externalisation', 'Externaliser certaines activités non critiques', 'project', 'long_term', 70, 'high'),
('Amélioration continue', 'Mettre en place une démarche d''amélioration continue', 'performance', 'long_term', 80, 'medium'),
('Support psychologique', 'Fournir un support psychologique aux employés', 'hr', 'immediate', 85, 'medium'),
('Révision des objectifs', 'Revoir et ajuster les objectifs fixés', 'project', 'short_term', 70, 'low'),
('Programme de reconnaissance', 'Lancer un programme de reconnaissance des mérites', 'hr', 'short_term', 75, 'low'),
('Optimisation des ressources', 'Optimiser l''allocation et l''utilisation des ressources', 'capacity', 'short_term', 80, 'medium'),
('Gestion du changement', 'Implémenter une stratégie de gestion du changement', 'hr', 'long_term', 85, 'medium'),
('Contrôle qualité renforcé', 'Renforcer les mesures de contrôle qualité', 'performance', 'short_term', 80, 'medium'),
('Communication de crise', 'Activer les procédures de communication de crise', 'project', 'immediate', 75, 'low'),
('Audit externe', 'Faire appel à un audit externe indépendant', 'project', 'short_term', 85, 'high'),
('Formation technique', 'Organiser des formations techniques spécialisées', 'performance', 'long_term', 80, 'medium'),
('Redéfinition des priorités', 'Revoir et redéfinir les priorités stratégiques', 'project', 'short_term', 75, 'low'),
('Amélioration environnement', 'Améliorer l''environnement de travail physique', 'hr', 'long_term', 70, 'high'),
('Surveillance rapprochée', 'Mettre en place une surveillance rapprochée', 'project', 'immediate', 65, 'low'),
('Plan de succession', 'Développer un plan de succession pour les postes clés', 'hr', 'long_term', 85, 'medium'),
('Négociation avec clients', 'Renégocier les termes avec les clients', 'project', 'short_term', 70, 'low'),
('Rotation des postes', 'Implémenter une rotation des postes', 'hr', 'long_term', 65, 'low'),
('Mise en conformité', 'Assurer la mise en conformité réglementaire', 'project', 'short_term', 90, 'medium'),
('Plan de communication', 'Élaborer un plan de communication structuré', 'project', 'short_term', 75, 'low'),
('Benchmark concurrentiel', 'Effectuer un benchmark avec la concurrence', 'project', 'short_term', 70, 'medium'),
('Innovation collaborative', 'Stimuler l''innovation par la collaboration', 'performance', 'long_term', 75, 'medium'),
('Gestion des risques', 'Renforcer la gestion des risques', 'project', 'short_term', 85, 'medium'),
('Programme de bien-être', 'Lancer un programme de bien-être au travail', 'hr', 'long_term', 80, 'medium'),
('Réduction de la bureaucratie', 'Simplifier les processus bureaucratiques', 'performance', 'long_term', 75, 'low'),
('Partenariats stratégiques', 'Développer des partenariats stratégiques', 'project', 'long_term', 80, 'high'),
('Flexibilité horaire', 'Introduire des horaires de travail flexibles', 'hr', 'short_term', 70, 'low'),
('Investissement technologique', 'Investir dans de nouvelles technologies', 'performance', 'long_term', 85, 'high'),
('Médiation de conflits', 'Organiser une médiation pour résoudre les conflits', 'hr', 'immediate', 80, 'low'),
('Diversification', 'Diversifier les activités ou les marchés', 'project', 'long_term', 75, 'high'),
('Formation cross-training', 'Former les employés sur plusieurs compétences', 'hr', 'long_term', 80, 'medium'),
('Optimisation des coûts', 'Lancer un programme d''optimisation des coûts', 'project', 'short_term', 70, 'low'),
('Amélioration de l''engagement', 'Mettre en place des mesures pour améliorer l''engagement', 'hr', 'long_term', 85, 'medium'),
('Standardisation', 'Standardiser les processus et procédures', 'performance', 'long_term', 75, 'medium'),
('Veille stratégique', 'Renforcer la veille stratégique et concurrentielle', 'project', 'short_term', 70, 'low'),
('Culture d''entreprise', 'Renforcer la culture d''entreprise', 'hr', 'long_term', 80, 'medium'),
('Gestion des talents', 'Améliorer la gestion des talents', 'hr', 'long_term', 85, 'medium'),
('Agilité organisationnelle', 'Développer l''agilité organisationnelle', 'performance', 'long_term', 80, 'medium'),
('Partenariat client', 'Renforcer le partenariat avec les clients', 'project', 'long_term', 75, 'low'),
('Innovation produit', 'Investir dans l''innovation produit', 'project', 'long_term', 85, 'high'),
('Amélioration continue', 'Implémenter une culture d''amélioration continue', 'performance', 'long_term', 85, 'medium'),
('Digitalisation', 'Accélérer la transformation digitale', 'performance', 'long_term', 90, 'high'),
('Gestion des performances', 'Renforcer la gestion des performances', 'performance', 'short_term', 80, 'low'),
('Communication transparente', 'Améliorer la transparence de la communication', 'hr', 'immediate', 75, 'low'),
('Développement des compétences', 'Investir dans le développement des compétences', 'hr', 'long_term', 85, 'medium'),
('Optimisation des processus', 'Optimiser les processus métier', 'performance', 'long_term', 85, 'medium'),
('Gestion de la qualité', 'Renforcer la gestion de la qualité', 'performance', 'short_term', 80, 'medium'),
('Planification stratégique', 'Réviser la planification stratégique', 'project', 'long_term', 85, 'low'),
('Gestion du stress', 'Mettre en place des programmes de gestion du stress', 'hr', 'short_term', 80, 'medium'),
('Innovation managériale', 'Introduire des innovations managériales', 'hr', 'long_term', 75, 'medium'),
('Amélioration de la productivité', 'Lancer des initiatives d''amélioration de productivité', 'performance', 'short_term', 80, 'medium'),
('Gestion des connaissances', 'Améliorer la gestion des connaissances', 'performance', 'long_term', 80, 'medium'),
('Développement durable', 'Intégrer les principes de développement durable', 'project', 'long_term', 75, 'medium'),
('Gestion des conflits', 'Améliorer la gestion des conflits', 'hr', 'short_term', 75, 'low'),
('Innovation collaborative', 'Favoriser l''innovation collaborative', 'performance', 'long_term', 80, 'medium'),
('Amélioration de l''efficacité', 'Optimiser l''efficacité opérationnelle', 'performance', 'short_term', 85, 'medium'),
('Gestion du temps', 'Améliorer la gestion du temps', 'performance', 'short_term', 70, 'low'),
('Leadership participatif', 'Promouvoir un leadership participatif', 'hr', 'long_term', 80, 'low'),
('Amélioration de la collaboration', 'Renforcer la collaboration entre équipes', 'hr', 'short_term', 75, 'low'),
('Gestion de la diversité', 'Améliorer la gestion de la diversité', 'hr', 'long_term', 75, 'medium'),
('Innovation technologique', 'Investir dans l''innovation technologique', 'performance', 'long_term', 90, 'high'),
('Amélioration de la communication', 'Optimiser les canaux de communication', 'hr', 'short_term', 75, 'low'),
('Gestion des compétences', 'Améliorer la gestion des compétences', 'hr', 'long_term', 85, 'medium'),
('Développement organisationnel', 'Investir dans le développement organisationnel', 'hr', 'long_term', 80, 'medium'),
('Amélioration de la flexibilité', 'Développer la flexibilité organisationnelle', 'hr', 'long_term', 75, 'medium'),
('Gestion de l''innovation', 'Améliorer la gestion de l''innovation', 'performance', 'long_term', 85, 'medium'),
('Développement des équipes', 'Investir dans le développement des équipes', 'hr', 'long_term', 80, 'medium'),
('Amélioration de la résilience', 'Développer la résilience organisationnelle', 'hr', 'long_term', 85, 'medium'),
('Gestion du changement culturel', 'Gérer le changement culturel', 'hr', 'long_term', 80, 'medium'),
('Innovation sociale', 'Promouvoir l''innovation sociale', 'hr', 'long_term', 75, 'medium'),
('Amélioration de l''adaptabilité', 'Développer l''adaptabilité organisationnelle', 'performance', 'long_term', 80, 'medium'),
('Gestion de l''apprentissage', 'Améliorer la gestion de l''apprentissage', 'hr', 'long_term', 85, 'medium'),
('Développement de la créativité', 'Stimuler la créativité dans l''organisation', 'performance', 'long_term', 75, 'medium'),
('Amélioration de la motivation', 'Renforcer la motivation des employés', 'hr', 'short_term', 80, 'low'),
('Gestion de l''excellence', 'Viser l''excellence opérationnelle', 'performance', 'long_term', 90, 'medium'),
('Innovation disruptive', 'Explorer l''innovation disruptive', 'project', 'long_term', 85, 'high'),
('Amélioration de la satisfaction', 'Améliorer la satisfaction des employés', 'hr', 'short_term', 80, 'medium'),
('Gestion de la performance collective', 'Optimiser la performance collective', 'performance', 'short_term', 85, 'low'),
('Développement de l''intelligence collective', 'Développer l''intelligence collective', 'hr', 'long_term', 80, 'medium'),
('Amélioration de l''agilité stratégique', 'Développer l''agilité stratégique', 'project', 'long_term', 85, 'medium'),
('Gestion de l''écosystème', 'Optimiser la gestion de l''écosystème', 'project', 'long_term', 80, 'high'),
('Innovation de rupture', 'Développer des innovations de rupture', 'project', 'long_term', 90, 'high');